services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8090:8090"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend